name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y meson ninja-build build-essential libgsl-dev libfftw3-dev
    
    - name: Setup build directory
      run: meson setup builddir
    
    - name: Compile
      run: meson compile -C builddir
    
    - name: Run
      run: ./builddir/zeldovich example.par
